spring:
  application:
    name: cosmo-cats

  # Настройки базы H2 (чтобы работало без установки Postgres)
  datasource:
    url: jdbc:h2:mem:cosmodb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # Настройки Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # Консоль H2 (чтобы можно было зайти в базу через браузер)
  h2:
    console:
      enabled: true